"""add_intelligence_domain_models

Revision ID: a2b5b89026e6
Revises: 779de7d32de8
Create Date: 2026-03-26 12:53:03.503562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b5b89026e6'
down_revision: Union[str, None] = '779de7d32de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create signals first (observations references it)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('monitor', 'mission', 'workflow', 'voice', 'user', 'api', 'upload', 'action_outcome', name='signalsourcetype'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.Enum('change_detected', 'data_extracted', 'threshold_breached', 'pattern_found', 'anomaly_detected', 'user_flagged', name='signaltype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_content_hash'), 'signals', ['content_hash'], unique=False)
    op.create_index(op.f('ix_signals_entity_id'), 'signals', ['entity_id'], unique=False)
    op.create_index(op.f('ix_signals_project_id'), 'signals', ['project_id'], unique=False)
    op.create_index(op.f('ix_signals_source_id'), 'signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('observation_type', sa.Enum('fact', 'measurement', 'quote', 'classification', 'comparison', 'temporal_change', 'relationship_observed', name='observationtype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_entity_id'), 'observations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_observations_finding_id'), 'observations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_observations_project_id'), 'observations', ['project_id'], unique=False)
    op.create_index(op.f('ix_observations_run_id'), 'observations', ['run_id'], unique=False)
    op.create_index(op.f('ix_observations_signal_id'), 'observations', ['signal_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias_type', sa.Enum('name_variant', 'external_id', 'url', 'phone', 'email', 'address', name='aliastype'), nullable=False),
    sa.Column('alias_value', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('subsidiary_of', 'competitor_of', 'partner_of', 'located_at', 'works_at', 'supplies_to', 'related_to', name='relationshiptype'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_from_entity_id'), 'entity_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_project_id'), 'entity_relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_to_entity_id'), 'entity_relationships', ['to_entity_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.Enum('trend', 'risk', 'opportunity', 'anomaly', 'summary', 'comparison', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('freshness_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('staleness_threshold_hours', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_entity_id'), 'insights', ['entity_id'], unique=False)
    op.create_index(op.f('ix_insights_project_id'), 'insights', ['project_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.Enum('investigate', 'monitor', 'contact', 'update', 'review', 'escalate', name='recommendationtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('suggested_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='recommendationpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', 'acted_on', name='recommendationstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_entity_id'), 'recommendations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_insight_id'), 'recommendations', ['insight_id'], unique=False)
    op.create_index(op.f('ix_recommendations_project_id'), 'recommendations', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.Enum('supporting', 'contradicting', 'contextual', name='evidencetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_insight_id'), 'evidence', ['insight_id'], unique=False)
    op.create_index(op.f('ix_evidence_observation_id'), 'evidence', ['observation_id'], unique=False)
    op.create_index(op.f('ix_evidence_recommendation_id'), 'evidence', ['recommendation_id'], unique=False)
    op.add_column('findings', sa.Column('observation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_findings_observation_id'), 'findings', ['observation_id'], unique=False)
    op.create_foreign_key(None, 'findings', 'observations', ['observation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_index(op.f('ix_findings_observation_id'), table_name='findings')
    op.drop_column('findings', 'observation_id')
    op.drop_index(op.f('ix_evidence_recommendation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_observation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_insight_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_recommendations_project_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_insight_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_entity_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_project_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_entity_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_content_hash'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_insights_project_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_entity_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_entity_relationships_to_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_project_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_from_entity_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_observations_signal_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_run_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_project_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_finding_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_entity_id'), table_name='observations')
    op.drop_table('observations')
    # ### end Alembic commands ###
