"""add action_requests action_policies action_executions action_outcomes tables

Revision ID: d128470fad95
Revises: 4905ec1a57ad
Create Date: 2026-03-26 14:11:03.825720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd128470fad95'
down_revision: Union[str, None] = '4905ec1a57ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_policies_project_id'), 'action_policies', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_policies_user_id'), 'action_policies', ['user_id'], unique=False)
    op.create_table('action_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('update_status', 'send_alert', 'trigger_workflow', 'trigger_monitor', 'create_task', 'generate_report', 'send_digest', 'queue_call', 'merge_entities', 'escalate', 'custom', name='actiontype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'executing', 'completed', 'failed', 'cancelled', 'expired', name='actionrequeststatus'), nullable=False),
    sa.Column('state_transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['action_policies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_requests_entity_id'), 'action_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_action_requests_project_id'), 'action_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_requests_recommendation_id'), 'action_requests', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_action_requests_user_id'), 'action_requests', ['user_id'], unique=False)
    op.create_table('action_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_request_id', sa.UUID(), nullable=False),
    sa.Column('executor_type', sa.Enum('system', 'celery_worker', 'external', name='executortype'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'rolled_back', name='executionstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('side_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_executions_action_request_id'), 'action_executions', ['action_request_id'], unique=False)
    op.create_table('action_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_request_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('outcome_type', sa.Enum('success', 'partial_success', 'failure', 'rejected_by_user', 'no_effect', 'needs_followup', name='outcometype'), nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_signal_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['action_executions.id'], ),
    sa.ForeignKeyConstraint(['feedback_signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_outcomes_action_request_id'), 'action_outcomes', ['action_request_id'], unique=False)
    op.create_index(op.f('ix_action_outcomes_execution_id'), 'action_outcomes', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_outcomes_execution_id'), table_name='action_outcomes')
    op.drop_index(op.f('ix_action_outcomes_action_request_id'), table_name='action_outcomes')
    op.drop_table('action_outcomes')
    op.drop_index(op.f('ix_action_executions_action_request_id'), table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_action_requests_user_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_recommendation_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_project_id'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_entity_id'), table_name='action_requests')
    op.drop_table('action_requests')
    op.drop_index(op.f('ix_action_policies_user_id'), table_name='action_policies')
    op.drop_index(op.f('ix_action_policies_project_id'), table_name='action_policies')
    op.drop_table('action_policies')
    sa.Enum('update_status', 'send_alert', 'trigger_workflow', 'trigger_monitor', 'create_task',
            'generate_report', 'send_digest', 'queue_call', 'merge_entities', 'escalate', 'custom',
            name='actiontype').drop(op.get_bind(), checkfirst=True)
    sa.Enum('pending_approval', 'approved', 'rejected', 'executing', 'completed', 'failed',
            'cancelled', 'expired', name='actionrequeststatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum('system', 'celery_worker', 'external', name='executortype').drop(op.get_bind(), checkfirst=True)
    sa.Enum('running', 'completed', 'failed', 'rolled_back', name='executionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum('success', 'partial_success', 'failure', 'rejected_by_user', 'no_effect',
            'needs_followup', name='outcometype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
